public enum Symbol
{
  NUL, IDENT, NUMLIT, TRUESYM, FALSESYM, PLUS,
  NOTSYM, MINUS, TIMES, SLASH, REMSYM, COLON,
  EQL, NEQ, LSS, LEQ, GTR, GEQ, LPAREN, RPAREN,
  COMMA, SEMICOLON, EOI, BECOMES, BEGINSYM, ENDSYM,
  IFSYM, THENSYM, ELSESYM, WHILESYM, LOOPSYM,
  GETSYM, PUTSYM, NEWLINE, NULLSYM, BOOLSYM,
  INTSYM, ISSYM, PROCSYM
}